// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT6Kaw5KwpU6K2ivXOJHLVbapf8YdnRso',
    appId: '1:447915397626:web:f4ddda3ebab5e8c7d6d443',
    messagingSenderId: '447915397626',
    projectId: 'ywork-1',
    authDomain: 'ywork-1.firebaseapp.com',
    storageBucket: 'ywork-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl9K2MLPTDjNqYbucj2k8BnhpElgl-jzA',
    appId: '1:447915397626:android:0c79eb37f74cb184d6d443',
    messagingSenderId: '447915397626',
    projectId: 'ywork-1',
    storageBucket: 'ywork-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_vCiV_vXclpWs09cv07Il4Bu2Xp78eqg',
    appId: '1:447915397626:ios:0f87d66762127e3dd6d443',
    messagingSenderId: '447915397626',
    projectId: 'ywork-1',
    storageBucket: 'ywork-1.appspot.com',
    androidClientId: '447915397626-o1d48lqfko6j7s839dm92eh5fg5fqu93.apps.googleusercontent.com',
    iosClientId: '447915397626-rjrpdack4gnol4qtk8003ghvca32bvun.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_vCiV_vXclpWs09cv07Il4Bu2Xp78eqg',
    appId: '1:447915397626:ios:0f87d66762127e3dd6d443',
    messagingSenderId: '447915397626',
    projectId: 'ywork-1',
    storageBucket: 'ywork-1.appspot.com',
    androidClientId: '447915397626-o1d48lqfko6j7s839dm92eh5fg5fqu93.apps.googleusercontent.com',
    iosClientId: '447915397626-rjrpdack4gnol4qtk8003ghvca32bvun.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );
}
